Two simple programs using the console.log
muarachmann/javaScript_tuto pull request #5
Opened 2018-10-23 10:24 UTC by Jumeb

2018-10-23 10:37 UTC, muarachmann requested changes
Great @Jumeb invite your friends over to contribute cause we have a project to build along side this. 
Now place the files hello.js and date.js in a common folder called basics

2018-10-23 14:16 UTC, Jumeb commented
The basic programs are now in the basics folder

2018-10-23 14:27 UTC, muarachmann approved these changes

2018-10-25 17:46 UTC, Jumeb commented
What I know about JavaScript.

2018-10-26 10:31 UTC, muarachmann approved these changes

2018-10-26 10:31 UTC, merged