A simple program to check if a word is a palindrome or not
muarachmann/javaScript_tuto pull request #6
Opened 2018-10-29 21:55 UTC by Jumeb

2018-10-30 06:50 UTC, Jumeb commented
Removed used of arrays and implemented use of concatenation.

2018-10-31 12:37 UTC, Jumeb commented
Made a simple dynamic color chooser for a webpage

2018-11-06 18:59 UTC, muarachmann requested changes

2018-11-06 18:59 UTC, muarachmann commented on Simple Webpage/Simple.html
> +            width: 100px;
please make this in a separate branch and folder called website

2018-11-24 19:29 UTC, merged